apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: webapp-config-map
      command:
        - /bin/sh
        - -c
        - |
          echo $APP_COLOR
