apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  MYSQL_DATABASE: c3FsMDE=         
  MYSQL_USER: dXNlcjE=             
  MYSQL_PASSWORD: cGFzc3dvcmQ=      
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM= 