apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
spec:
  containers:
    - name: print-env-container
      image: ubuntu
      env:
        - name: GREETING
          value: "Welcome to"
        - name: COMPANY
          value: "DevOps"
        - name: GROUP
          value: "Industries"
      command:
        - /bin/bash
        - -c
        - |
          echo "$(GREETING) $(COMPANY) $(GROUP)"
          sleep 3600
