apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-liveness-probe
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /test.html
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
