apiVersion: v1
kind: Pod
metadata:
  name: nodejs-health-check
spec:
  containers:
    - name: nodejs
      image: nginx 
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
